# Generated by Django 2.2.6 on 2019-10-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural")
    ]

    operations = [
        migrations.CreateModel(
            name="TestPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("test_translatable_field", models.TextField(blank=True)),
                ("test_synchronized_field", models.TextField(blank=True)),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
