# Generated by Django 2.2.6 on 2019-10-07 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_initial_data'),
        ('wagtail_localize_pontoon_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='testpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
