# Generated by Django 2.2.9 on 2020-01-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_pontoon", "0006_auto_20191007_1700"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pontoonresourcesubmission", name="push_log",
        ),
        migrations.RemoveField(
            model_name="pontoonresourcesubmission", name="resource",
        ),
        migrations.RemoveField(
            model_name="pontoonresourcesubmission", name="revision",
        ),
        migrations.RemoveField(
            model_name="pontoonresourcetranslation", name="language",
        ),
        migrations.RemoveField(
            model_name="pontoonresourcetranslation", name="revision",
        ),
        migrations.RemoveField(
            model_name="pontoonresourcetranslation", name="submission",
        ),
        migrations.RemoveField(model_name="pontoonsynclogresource", name="language",),
        migrations.RemoveField(model_name="pontoonsynclogresource", name="log",),
        migrations.RemoveField(model_name="pontoonsynclogresource", name="resource",),
        migrations.DeleteModel(name="PontoonResource",),
        migrations.DeleteModel(name="PontoonResourceSubmission",),
        migrations.DeleteModel(name="PontoonResourceTranslation",),
        migrations.DeleteModel(name="PontoonSyncLog",),
        migrations.DeleteModel(name="PontoonSyncLogResource",),
    ]
